config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :documents
  root :to => "documents#index"
  get 'documents/words' => 'document#words'  

  match "*path" => redirect("/"), via: :get

end

app/models/document.rb
class Document < ActiveRecord::Base
  
  belongs_to :user
  has_and_belongs_to_many :words
  validates_presence_of :content, :title
  before_destroy {|document| document.delete_words}

  def delete_words
    self.words.each do |word|
       first_word = Word.find_by(content: word.content)
       first_word.decrement!(:count)
       if first_word.count==0
         first_word.destroy
       end
     end
     self.words.destroy_all
  end

  def add_words(words_list)
    words_list.each do |word|
      first_word = Word.find_by(content: word)
      if first_word.nil?
        new_word = Word.new(:content => word, :count => 1)
        new_word.save
        self.words<<new_word   
      else
        first_word.increment!(:count)
        self.words<<first_word
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :documents, dependent: :destroy
end

app/models/word.rb
class Word < ActiveRecord::Base
  has_and_belongs_to_many :documents
  validates :count, numericality: true
  validates :content, format: { with: /\A[a-zA-Z]+\z/}
  validates_presence_of :content, :count
  
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || signed_in_root_path(resource)
  end



end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  require 'html/sanitizer'

  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_filter :require_permission, only: [:edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @my_documents = Document.where(:user_id => current_user).order(created_at: :desc)
    @other_documents = Document.where.not(:user_id => current_user).order(created_at: :desc)
    
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @my_document = Document.new
   
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @my_document = Document.new(my_document_params)
    @my_document.user_id = current_user.id

    respond_to do |format|
      if @my_document.save

        words_list = split_into_words(@my_document.content)
        @my_document.add_words(words_list) unless words_list.empty?

        format.html { redirect_to @my_document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @my_document }
      else
        format.html { render :new }
        format.json { render json: @my_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    my_document_old = @my_document

    respond_to do |format|
      if @my_document.update(my_document_params)

        my_document_old.delete_words
        words_list = split_into_words(@my_document.content)
        @my_document.add_words(words_list) unless words_list.empty?

        format.html { redirect_to @my_document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @my_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @my_document.delete_words

    @my_document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
   def set_document
     @my_document = Document.find(params[:id])
   end

   def require_permission
     if current_user.id != Document.find(params[:id]).user_id
       redirect_to root_path
     end
   end
   
   def my_document_params
     params.require(:document).permit(:content, :title)
   end

   def split_into_words(content)
     full_sanitizer = HTML::FullSanitizer.new
     clean_text = full_sanitizer.sanitize(content)
     words_list = clean_text.split(/[\s,.;!?]/).select{|_w| _w =~ /^[a-zA-Z]+$/} unless clean_text.nil?
     #logger.debug "Word list: #{words_list}"
     return words_list    
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(object)
	  concat(content_tag(:ul) do
	    object.errors.full_messages.each do |msg|
	      concat content_tag(:li, msg)
	    end
      end)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def created_at_format(document)
    document.created_at.strftime("%d %b. %Y   %H:%M")
  end
end

app/views/documents/_form.html.erb
<% if @my_document.errors.any? %>
 <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
      <ul>
      <% @my_document.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
 </div>
 <% end %>
<%= form_for(@my_document) do |f| %>

  <%= f.label :title, :class => "sr-only" %><br>
  <%= f.text_area :title, :class => "form-control", :placeholder => "Title", :class => "doc_title" %>
  <%= f.label :content, :class => "sr-only" %><br>
  <%= f.text_area :content, :class => "form-control", :placeholder => "Content", :class => "doc_content tinymce" %><br />
  <%= f.submit "Done", :class => "btn btn-warning" %>
<% end %> <br />

app/views/documents/edit.html.erb
<%= tinymce_assets %>
<main>
  <section class="container">
    <div class="col-xs-10 col-sm-6 col-md-6 col-lg-6 col-centered">
		<h1>Edit document</h1>

		<%= render 'form' %>

		<%= button_to 'Back', documents_path, :class => "btn btn-default", method: :get %>

    </div>
  </section>
</main>

<%= tinymce %>

app/views/documents/index.html.erb
<main>
  <section class="container">
   
    <h1>Dashboard</h1>
    <%= link_to 'New Document', new_document_path, :class => "btn btn-primary", 'data-no-turbolink' => false  %> <br />
    <div class="dashboard-my-docs">
      <h3>My documents</h3>
      <%if @my_documents.empty? %>
        There are currently no documents created by you.   
      <% end %>

      <% @my_documents.each do |document| %>
        <article class="document-box">
          <p><%= link_to  "[#{document.title}]", document_path(document), class: "document-title-link" %></p>
          <p>Created by: <%= document.user.email %></p>
          <p>Created at: <%= created_at_format(document) %></p>
          <%= link_to  'Edit', edit_document_path(document), :class => "btn btn-default btn-sm col-xs-offset-1 col-xs-5 col-sm-offset-1 col-sm-5 col-md-offset-2 col-md-4 col-lg-offset-2 col-lg-4", 'data-no-turbolink' => false  %>
          <%= link_to 'Delete', document, :method => :delete, data: { confirm: 'Are you sure?' },  :class => "btn btn-default btn-sm col-xs-5 col-sm-5 col-md-4  col-lg-4 "%> <br /> <br />   
        </article> 
      <% end %>
    </div>

    <div class="dashboard-other-docs">
      <h3>Other documents</h3>
      <%if @other_documents.empty? %>
        There are currently no documents created by others.   
      <% end %>
      <% @other_documents.each do |document| %>
        <article class="document-box">
          <p><%= link_to  "[#{document.title}]", document_path(document), class: "document-title-link"  %></p>
          <p>Created by: <%= document.user.email %></p>
          <p>Created at: <%= created_at_format(document) %></p>
          
        </article> 
      <% end %>
    </div>
  </section>
</main>
         
          

app/views/documents/new.html.erb
<%= tinymce_assets %>
<main>
  <section class="container">
    <div class="col-xs-10 col-sm-6 col-md-6 col-lg-6 col-centered">
		<h1>New document</h1>

		<%= render 'form' %>

		<%= button_to 'Back', documents_path, :class => "btn btn-default", method: :get %>

    </div>
  </section>
</main>

<%= tinymce %>

app/views/documents/show.html.erb
<main>
  <section class="preview">
    <div class="col-xs-10 col-sm-6 col-md-6 col-lg-6 col-centered">  	   
      <h1>Preview</h1>
      <h2><li><%= @my_document.title %></li></h2> <br/>

      <p class="show-document-text"><%= sanitize(@my_document.content) %></p><br />
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 show-document-buttons"> 
       <%= link_to 'Edit', edit_document_path(@my_document), :class => "btn btn-warning", 'data-no-turbolink' => false %><br /><br />
       <%= link_to 'Back to list', documents_path, :class => "btn btn-default"%><br />
     </div>
 
    </div>
  </section>
</main>

app/views/layouts/_active_link.html.erb
<% if current_page? path %>
  <li class="active"><%= link_to link_text, path %></li>
<% else %>
  <li><%= link_to link_text, path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Documents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
  <nav class ="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Dashboard", documents_path, :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse mainnav">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><p class="navbar-text">Logged in as <strong><%= current_user.email %></strong>.</p></li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
            <li><%= link_to "Cancel my account",  {:controller => '/devise/registrations',
              :action => 'destroy', :email => current_user.email}, data: { confirm: "Are you sure you want to cancel your account? All your data will be permanently destroyed." }, method: :delete %> </li>
          <% else %>
            <%= render :partial => "/layouts/active_link", :locals => {:path =>  new_user_session_path, :link_text => "Log in"} %>
            <%= render :partial => "/layouts/active_link", :locals => {:path =>  new_user_registration_path, :link_text => "Sign up"} %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>


  <% if notice %>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
        <%= notice %>
      </div>
    </div>
  <% end %>
  <% if alert %>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
        <%= alert %>
      </div>
    </div>
  <% end %>

  <%= yield %>
 
</body>
</html>